version: "3.4"

networks:
   local:
     driver: bridge

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel-php
    container_name: laravel-php
    depends_on:
      - db
    restart: always
    volumes:
      - ./:/var/www/backend
      - ./docker/php/conf.d/php.dev.ini/:/usr/local/etc/php/conf.d/laravel.ini
      - "phpsocket:/var/run"
    networks:
      - local
    external_links:
      - db

  db:
    image: postgres:12-alpine
    container_name: lar-db
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    ports:
      - "5432:5432"
    networks:
      - local

  nginx:
    build:
       context: .
       dockerfile: docker/nginx/Dockerfile
    image: nginx:1.17-alpine
    container_name: laravel-nginx
    depends_on:
      - php
    volumes:
      - ./:/var/www/backend
      - "phpsocket:/var/run"
    ports:
      - ${NGINX_PORT}:80
    links:
      - php
    networks:
      - local

volumes:
  phpsocket:
  webdav_data:
